export enum Users {
  // 'yTJuwi0wiKeWRmoZdpNsOcxoeUA2' = 'Szymon Sobol',
  "5f0StLUdrFQkqTfy4Fbzahx26592" = "Mateusz Sepioł",
  "QScmRVQyJ5VyyYu0r8wDU4Ybasi2" = "Maciej Sobol",
  "S92wzyyzU5aAUgNjlS6EN1OJQVh2" = "Łukasz Ligięza",
  // 'abEnp61lLeTEpJsGiyxPhXoPB582' = 'Ola Poziomska',
  // 'TSudtVlqC6Rs8aVkcjeZQeMbPN73' = 'Arek Suwalski',
  // "d77n8QjyECcc9DcQAQmf3pOjlTs1" = "Michał Karwat",
  "DfTerE7W5DgYuFksjM1qpkyLltr1" = "Michał Orlikowski",
  "q4513BAFbDM9lTPeALv7BYfZPml1" = "Tomasz Będkowski",
  "rFx1venNKKTRgocPA92DFcoIqgd2" = "Dawid Poziomski",
  // "CccBEcS8N1M5rGQczzatbmbbiHj2" = "Witek Suwalski",
  // 'KTRZR26iTZXj6pJmty7rK14cfij1' = 'Artur Szombierski',
  // '9jIA1qkuJCN7QXnPdCcBqqRgBd72' = 'Bartek Jagusiak',
  // 'J5H1sgUWx7hmRP3XRlQ0BWSeMzH2' = 'Ewa Skibińska',
  "NMcPJCsf2febUU7desvk92HWZCb2" = "Roksana Półtorak-Będkowska",
  // "t7G3UDgXPRYF47hEi8ZARU7ylwf2" = "Dominika Orlikowska",
}
